"use server";

/**
 * Email Service for Chalk
 * Resend를 사용한 이메일 발송 서비스
 */

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const FROM_EMAIL = process.env.FROM_EMAIL || "Chalk <noreply@chalk.app>";
const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

export interface EmailResult {
    success: boolean;
    messageId?: string;
    error?: string;
}

/**
 * 이메일 발송
 */
async function sendEmail(
    to: string,
    subject: string,
    html: string
): Promise<EmailResult> {
    if (!RESEND_API_KEY) {
        console.log("[Email] Demo mode - API key not set");
        console.log(`[Email] Would send to: ${to}`);
        console.log(`[Email] Subject: ${subject}`);
        return { success: true, messageId: "demo-mode" };
    }

    try {
        const response = await fetch("https://api.resend.com/emails", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${RESEND_API_KEY}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                from: FROM_EMAIL,
                to: [to],
                subject,
                html,
            }),
        });

        if (!response.ok) {
            const error = await response.text();
            throw new Error(`Resend API error: ${error}`);
        }

        const data = await response.json();
        return { success: true, messageId: data.id };
    } catch (err: any) {
        console.error("[Email] Error:", err);
        return { success: false, error: err.message };
    }
}

/**
 * 세션 리포트 이메일 템플릿
 */
function getReportEmailTemplate(params: {
    studentName: string;
    subjectName: string;
    sessionDate: string;
    summary: string;
    topicsCount: number;
    reportUrl: string;
}): string {
    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Session Report</title>
</head>
<body style="margin: 0; padding: 0; background-color: #050510; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
    <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
        <!-- Header -->
        <div style="text-align: center; margin-bottom: 40px;">
            <div style="display: inline-block; background-color: #10b981; padding: 8px 16px; border-radius: 8px; margin-bottom: 16px;">
                <span style="color: #000; font-weight: bold; font-size: 14px; letter-spacing: 2px;">CHALK</span>
            </div>
            <h1 style="color: #ffffff; font-size: 28px; margin: 0; font-weight: 800;">
                ${params.studentName}'s<br>
                <span style="color: #10b981;">Learning Report</span>
            </h1>
        </div>

        <!-- Content Card -->
        <div style="background-color: #18181b; border: 1px solid #27272a; border-radius: 24px; padding: 32px; margin-bottom: 24px;">
            <p style="color: #a1a1aa; font-size: 12px; text-transform: uppercase; letter-spacing: 2px; margin: 0 0 8px 0;">
                ${params.subjectName} • ${params.sessionDate}
            </p>

            <h2 style="color: #ffffff; font-size: 18px; margin: 24px 0 12px 0; font-weight: 600;">
                Session Summary
            </h2>
            <p style="color: #d4d4d8; font-size: 16px; line-height: 1.6; margin: 0 0 24px 0;">
                ${params.summary || "A productive tutoring session was completed."}
            </p>

            <div style="display: flex; gap: 16px; margin-bottom: 24px;">
                <div style="background-color: #10b981; background-opacity: 0.1; padding: 16px; border-radius: 12px; flex: 1; text-align: center;">
                    <p style="color: #10b981; font-size: 28px; font-weight: bold; margin: 0;">${params.topicsCount}</p>
                    <p style="color: #71717a; font-size: 12px; margin: 4px 0 0 0;">Topics Covered</p>
                </div>
            </div>

            <a href="${params.reportUrl}"
               style="display: block; background-color: #10b981; color: #000000; text-decoration: none; padding: 16px 32px; border-radius: 12px; font-weight: 600; text-align: center; font-size: 16px;">
                View Full Report
            </a>
        </div>

        <!-- Footer -->
        <div style="text-align: center; padding: 20px;">
            <p style="color: #52525b; font-size: 12px; margin: 0;">
                This report was generated by Chalk Intelligence System.<br>
                You're receiving this because you're listed as a parent/guardian.
            </p>
        </div>
    </div>
</body>
</html>
    `.trim();
}

/**
 * 학부모에게 세션 리포트 이메일 발송
 */
export async function sendReportEmail(params: {
    parentEmail: string;
    studentName: string;
    subjectName: string;
    sessionDate: string;
    summary: string;
    topicsCount: number;
    shareToken: string;
}): Promise<EmailResult> {
    const reportUrl = `${APP_URL}/parent/report/${params.shareToken}`;

    const html = getReportEmailTemplate({
        studentName: params.studentName,
        subjectName: params.subjectName,
        sessionDate: new Date(params.sessionDate).toLocaleDateString('en-US', {
            month: 'long',
            day: 'numeric',
            year: 'numeric',
        }),
        summary: params.summary,
        topicsCount: params.topicsCount,
        reportUrl,
    });

    return sendEmail(
        params.parentEmail,
        `📚 ${params.studentName}'s Learning Report - ${params.subjectName}`,
        html
    );
}

/**
 * 테스트 이메일 발송
 */
export async function sendTestEmail(to: string): Promise<EmailResult> {
    const html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h1>Test Email from Chalk</h1>
            <p>If you received this, your email configuration is working correctly!</p>
            <p style="color: #10b981; font-weight: bold;">✓ Email service connected</p>
        </div>
    `;

    return sendEmail(to, "Test Email from Chalk", html);
}
